/* Seção 7 e 8 */

/* Lidando com valores NULO: A realidade é que não sabemos de fato o que está no valor 'NULL'
assim não podemos usar igualdade, sendo necessário explicitar que você está buscando um valor nulo */

SELECT NOME, ENDERECO, EMAIL FROM CLIENTE
WHERE EMAIL IS NOT NULL;

SELECT NOME, ENDERECO, EMAIL FROM CLIENTE
WHERE EMAIL IS NULL;

/* UPDATE: atualizar infos 
Sempre usar um select antes e o WHERE (OBRIGATORIO) */

UPDATE CLIENTE
SET EMAIL = "LILIAN@HOTMAIL.COM"
WHERE NOME = "LILIAN";


/* DELETE: deleta observações. Sempre usar o WHERE 

Dica: Sempre fazer um COUNT() */

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- 6 obs
SELECT COUNT(*) FROM CLIENTE -- 1
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';


/* MODELAGEM 

PRIMEIRA FORMA NORMAL 
	1º Todo vertor é uma nova tabela
	2º Todo campo divisível é uma nova tabela
	3º Todo precisa de uma identidade, ou seja, um campo único. Primary key, que pode ser natural (ex. CPF) ou artificial 
 */ 
 
 /* Cardinalidade: Quem define a cardiladade é a regra de negócio
 
 (0, n)
 (0, 1)
 (1, n)
 (1, 1)
 
 O primeiro algorismo (0 ou 1) representa a obrigatoriedade. Se é ou não obrigatorio o preenchemento do dado ou seja no minimo 1.
 O segundo algorismo (n ou 1) representa a cardinalidade. Já aqui defini se será 1 ou mais de 1, ou seja, vai determinar o máximo.

Deve-se ler de acordo com o segundo algorismo. 

*/

/*
CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA
QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE
REGISTROS */

/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA
CARDINALIDADE N */

CREATE DATABASE COMERCIO;
USE COMERCIO; 

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, -- O próprio banco implementar a chave primaria
	NOME VARCHAR() NOT NULL, -- (1,1) Todo mundo tem nome, não pode ser em branco e só um é necessário
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50), -- Estabelecer dominino, opções pré estabelecida (so existe no mysql)
	CPF VARCHAR(15) UNIQUE 
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL, 
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50), 
	CPF VARCHAR(15) UNIQUE 
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	RUA VARCHAR(30) NOT NULL, 
	BAIRRO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO CHAR(11) NOT NULL, 
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'MG', 'B. HORIZONTE', 'RUA ANTONIO SA','CENTRO',4);
INSERT INTO ENDERECO VALUES(NULL, 'RJ','RIO DE JANEIRO','RUA CAPITAO HERMES','CENTRO',1);
INSERT INTO ENDERECO VALUES(NULL, 'SP','SAO PAULO','RUA PRES VARGAS','JARDINS',3);
INSERT INTO ENDERECO VALUES(NULL,'RJ','RIO DE JANEIRO','RUA ALFANDEGA','ESTACIO',2);
INSERT INTO ENDERECO VALUES(NULL,'RJ','RIO DE JANEIRO','RUA DO OUVIDOR','FLAMENGO',6);
INSERT INTO ENDERECO VALUES(NULL, 'ES','VITORIA','RUA URUGUAIANA','CENTRO',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);




